/**
 * Plantillas pregeneradas de enemigos para Cyberpunk RED.
 *
 * Basadas en los arquetipos y niveles de blindaje descritos en el manual
 * básico de Cyberpunk RED (armaduras: Kevlar SP7, Armadura ligera SP11,
 * Armadura media SP12, Armadura pesada SP13, Antimotín/Flak SP15,
 * Metalgear SP18) y en los tamaños típicos de cargador de las armas
 * más habituales (Pistola media 12, Pistola pesada 8, Pistola muy pesada 8,
 * SMG 30, Rifle de asalto 25, Escopeta 4, Rifle de precisión 4).
 *
 * Todas las plantillas son sugerencias homebrew para uso local.
 */

// eslint-disable-next-line no-unused-vars
const BUILT_IN_TEMPLATES = [
  {
    category: "Civiles",
    entries: [
      {
        key: "civil-desarmado",
        name: "Civil desarmado",
        maxHp: 20,
        bodySp: 0,
        headSp: 0,
        magazine: 0,
        description: "Peatón sin blindaje. No devuelve fuego.",
      },
      {
        key: "civil-armado",
        name: "Civil armado",
        maxHp: 25,
        bodySp: 4,
        headSp: 0,
        magazine: 8,
        description: "Ciudadano con chaleco textil y pistola pesada.",
      },
      {
        key: "media",
        name: "Media / Reportero",
        maxHp: 30,
        bodySp: 7,
        headSp: 7,
        magazine: 8,
        description: "Periodista de calle con Kevlar y pistola media.",
      },
    ],
  },
  {
    category: "Bandas y calle",
    entries: [
      {
        key: "maton",
        name: "Matón callejero",
        maxHp: 30,
        bodySp: 7,
        headSp: 7,
        magazine: 8,
        description: "Kevlar (SP7) + pistola pesada. Amenaza básica.",
      },
      {
        key: "ganger-melee",
        name: "Ganger a melee",
        maxHp: 35,
        bodySp: 11,
        headSp: 11,
        magazine: 0,
        description: "Armadura ligera (SP11), machete o cadena. Solo cuerpo a cuerpo.",
      },
      {
        key: "booster-smg",
        name: "Booster con SMG",
        maxHp: 40,
        bodySp: 11,
        headSp: 11,
        magazine: 30,
        description: "Armadura ligera + subfusil de 30 balas.",
      },
      {
        key: "chromer",
        name: "Chromer (cyberware ligero)",
        maxHp: 45,
        bodySp: 11,
        headSp: 11,
        magazine: 25,
        description: "Miembros cibernéticos y rifle de asalto.",
      },
    ],
  },
  {
    category: "Fuerzas de la ley",
    entries: [
      {
        key: "ncpd-agente",
        name: "Agente NCPD",
        maxHp: 35,
        bodySp: 11,
        headSp: 11,
        magazine: 12,
        description: "Uniforme reforzado (SP11) y pistola media.",
      },
      {
        key: "ncpd-detective",
        name: "Detective NCPD",
        maxHp: 40,
        bodySp: 11,
        headSp: 7,
        magazine: 8,
        description: "Placa, gabardina blindada y pistola pesada.",
      },
      {
        key: "cswat",
        name: "C-SWAT",
        maxHp: 45,
        bodySp: 15,
        headSp: 15,
        magazine: 30,
        description: "Traje antimotín (SP15) + subfusil de asalto.",
      },
      {
        key: "maxtac",
        name: "Agente MaxTac",
        maxHp: 50,
        bodySp: 15,
        headSp: 15,
        magazine: 25,
        description: "Élite anti-cyberpsico. Blindaje pesado y rifle de asalto.",
      },
    ],
  },
  {
    category: "Corporativo",
    entries: [
      {
        key: "guardia-corpo",
        name: "Guardia corporativo",
        maxHp: 40,
        bodySp: 13,
        headSp: 13,
        magazine: 25,
        description: "Armadura media (SP13) + rifle de asalto.",
      },
      {
        key: "solo-corpo",
        name: "Solo (mercenario corpo)",
        maxHp: 45,
        bodySp: 15,
        headSp: 13,
        magazine: 30,
        description: "Antimotín en cuerpo, media en cabeza. Subfusil de asalto.",
      },
      {
        key: "ejecutivo",
        name: "Ejecutivo armado",
        maxHp: 30,
        bodySp: 11,
        headSp: 7,
        magazine: 8,
        description: "Traje con placa ligera y pistola pesada oculta.",
      },
      {
        key: "netrunner",
        name: "Netrunner de apoyo",
        maxHp: 30,
        bodySp: 7,
        headSp: 7,
        magazine: 12,
        description: "Kevlar y pistola media. Peligro real dentro de la RED.",
      },
      {
        key: "tecno",
        name: "Tecno / Ingeniero",
        maxHp: 30,
        bodySp: 7,
        headSp: 7,
        magazine: 8,
        description: "Herramientas y pistola pesada. Apoyo técnico.",
      },
    ],
  },
  {
    category: "Élite y especiales",
    entries: [
      {
        key: "nomada-guerrero",
        name: "Nómada guerrero",
        maxHp: 40,
        bodySp: 11,
        headSp: 11,
        magazine: 4,
        description: "Armadura ligera + escopeta. Duro y difícil de derribar.",
      },
      {
        key: "trauma-team",
        name: "Trauma Team (escolta)",
        maxHp: 45,
        bodySp: 13,
        headSp: 13,
        magazine: 25,
        description: "Paramédico armado con blindaje medio y rifle de asalto.",
      },
      {
        key: "ronin",
        name: "Ronin (asesino a sueldo)",
        maxHp: 45,
        bodySp: 13,
        headSp: 11,
        magazine: 4,
        description: "Blindaje medio y rifle de precisión.",
      },
      {
        key: "cyberpsycho",
        name: "Cyberpsycho",
        maxHp: 60,
        bodySp: 15,
        headSp: 15,
        magazine: 0,
        description: "Blindaje subdérmico brutal. Melee devastador. Prioridad máxima.",
      },
      {
        key: "boss",
        name: "Antagonista / Jefe",
        maxHp: 70,
        bodySp: 18,
        headSp: 15,
        magazine: 8,
        description: "Metalgear en cuerpo + blindaje pesado en cabeza. Villano final.",
      },
      {
        key: "dron",
        name: "Dron de vigilancia",
        maxHp: 25,
        bodySp: 11,
        headSp: 11,
        magazine: 25,
        description: "Blindaje ligero + ametralladora ligera.",
      },
      {
        key: "custom",
        name: "Personalizado",
        maxHp: 30,
        bodySp: 7,
        headSp: 7,
        magazine: 6,
        description: "Punto de partida en blanco para ajustar a mano.",
      },
    ],
  },
];
